// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class nuevoscampos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nuevoscampos));
        
        string IMigrationMetadata.Id
        {
            get { return "201912130013043_nuevos-campos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
